BodyWeight/BodyWeight/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', include('curd_body_weight.urls'))
]

BodyWeight/curd_body_weight/urls.py
from django.urls import path
from .views import index, show, create_view, update, delete

app_name = 'bodyweight'
urlpatterns = [
    path('',index, name='index'),
    path('show/<int:id>', show, name='show'),
    path('create', create_view, name='create'),
    path('update/<int:id>', update, name='update'),
    path('delete/<int:id>', delete, name='delete'),
]

BodyWeight/curd_body_weight/models.py
from django.db import models

# Create your models here.
class modelBodyWeight(models.Model):
    tanggal = models.DateField()
    max_val = models.IntegerField()
    min_val = models.IntegerField()

    class Meta:
        db_table = 'bodyweight'

BodyWeight/curd_body_weight/forms.py
from django.forms import ModelForm
from django.utils.translation import gettext_lazy as _
from .models import modelBodyWeight

class weightForm(ModelForm):
    class Meta:
        model =  modelBodyWeight
        fields = ('tanggal', 'max_val', 'min_val')
        labels = {
            'tanggal': _('Tanggal'),
            'max_val': _('Berat Max'),
            'min_val': _('Berat Min')
        }
        error_messages = {
            'tanggal': {
                'required': _("Judul harus diisi."),
            },
            'max_val': {
                'required': _("Deskripsi harus diisi."),
            },
            'min_val': {
                'required': _("Deskripsi harus diisi."),
            },            
        }

BodyWeight/curd_body_weight/views.py
from django.shortcuts import render, redirect
from django.http import Http404
from .models import modelBodyWeight
from .forms import weightForm
from django.contrib import messages


def index(request):
    '''
    This function will get all data from dbsqlite then render into index.html
    '''
    bW = modelBodyWeight.objects.all()
    context = {
        'bodyweight': bW
    }
    return render(request, 'curd_body_weight/index.html', context)


def show(request, id):
    '''
    This function will data with selected id from dbsqlite then render into detail.html
    '''
    try:
        bw = modelBodyWeight.objects.get(pk=id)
        context = {
            'bodyweight': bw
        }
    except modelBodyWeight.DoesNotExist:
        raise Http404("Data tidak ditemukan.")
    return render(request, 'curd_body_weight/detail.html', context)

def create_view(request):
    '''
    This function show form to imput new record
    '''
    if request.method == 'POST':
        new_task = weightForm(request.POST)
        if new_task.is_valid():
            new_task.save()
            messages.success(request, 'Sukses Menambah Record baru.')
            return redirect('bodyweight:index')

    else:
        form = weightForm()
        return render(request, 'curd_body_weight/form.html', {'form': form})

def update(request, id):
    '''
    This function will allow us to update selected record
    '''
    try:
        task = modelBodyWeight.objects.get(pk=id)
    except modelBodyWeight.DoesNotExist:
        raise Http404("Record tidak ditemukan.")
    if request.method == 'POST':
        form = weightForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
            messages.success(request, 'Sukses Mengubah Record.')
            return redirect('bodyweight:index')
    else:
        form = weightForm(instance=task)
    return render(request, 'curd_body_weight/form.html', {'form': form})

def delete(request, id):
    '''
    This function will delete selected record
    '''
    try:
        task = modelBodyWeight.objects.get(pk=id)
        task.delete()
        messages.success(request, 'Sukses Menghapus Record.')
        return redirect('bodyweight:index')

    except modelBodyWeight.DoesNotExist:
        raise Http404("Record tidak ditemukan.")

BodyWeight/curd_body_weight/templates/curd_body_weight/detail.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Body Weight App</title>

    <style>
      body {
        margin-top: 30px;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <h1>Detail Task</h1>

      <div>
        <a href="{% url 'bodyweight:index' %}" class="btn btn-success">Kembali ke Daftar</a>
      </div>

      <br>

      <div>
        {% load mathfilters %}
        <table class="table table-bordered table-striped">
          <thead>
              <tr>
                <th width="25%">Tanggal</th>
                <th width="10%">Max</th>
                <th width="10%">Min</th>
                <th width="10%">Perbedaan</th>
              </tr>
          </thead>
          <tbody>
            <tr>
              <td>{{ bw.tanggal }}</td>
              <td>{{ bw.max_val }}</td>
              <td>{{ bw.min_val }}</td>
            </tr>
          </tbody>
        </table>
  
      </div>
  </div>
 
  </body>
</html>

BodyWeight/curd_body_weight/templates/curd_body_weight/form.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Body Weight App</title>

    <style>
      body {
        margin-top: 30px;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <h1>New Weight Form</h1>

      <div>
        <a href="{% url 'bodyweight:index' %}" class="btn btn-success">Back to List</a>
      </div>

      <br>

      <div>
        {% load widget_tweaks %}

        <form method="post" novalidate>
          {% csrf_token %}

          {% if form.non_field_errors %}
            <div class="alert alert-danger" role="alert">
              {% for error in form.non_field_errors %}
                {{ error }}
              {% endfor %}
            </div>
          {% endif %}

          {% for field in form.visible_fields %}
            <div class="form-group">
              {{ field.label_tag }}

              {% if form.is_bound %}
                {% if field.errors %}
                  {% render_field field class="form-control is-invalid" %}
                  {% for error in field.errors %}
                    <div class="invalid-feedback">
                      {{ error }}
                    </div>
                  {% endfor %}
                {% else %}
                  {% render_field field class="form-control is-valid" %}
                {% endif %}
              {% else %}
                {% render_field field class="form-control" %}
              {% endif %}

              {% if field.help_text %}
                <small class="form-text text-muted">{{ field.help_text }}</small>
              {% endif %}
            </div>
          {% endfor %}

          <button type="submit" class="btn btn-primary">Submit</button>
        </form>
      </div>
  </div>
 
  </body>
</html>

BodyWeight/curd_body_weight/templates/curd_body_weight/index.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Body Weight App</title>

    <style>
      body {
        margin-top: 30px;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <h1>Body Weight List</h1>

      <div>
      {% if messages %}
      
        	{% for message in messages %}
        	<div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
          	<button type="button" class="close" data-dismiss="alert" aria-label="Close">
            		<span aria-hidden="true">&times;</span>
          	</button>
            	{{ message | safe }}
        	</div>
        	{% endfor %}
        
      {% endif %}
      </div>

      <div>
      	<a href="{% url 'bodyweight:create'  %}" class="btn btn-success">Tambah Baru</a>
      </div>

      <br>
      {% load mathfilters %}
      <table class="table table-bordered table-striped">
          <thead>
              <tr>
                  <th width="5%">ID</th>
                  <th width="25%">Tanggal</th>
                  <th width="10%">Max</th>
                  <th width="10%">Min</th>
                  <th width="10%">Perbedaan</th>
                  <th width="25%">Update</th>
              </tr>
          </thead>
          <tbody>
            {% if bodyweight %}
              {% for bw in bodyweight %}
              <tr>
                  <td>{{ bw.id }}</td>
                  <td>{{ bw.tanggal }}</td>
                  <td>{{ bw.max_val }}</td>
                  <td>{{ bw.min_val }}</td>
                  <td>{{ bw.max_val | sub:bw.min_val }}</td>
                  <td>
                      <a href="{% url 'bodyweight:show' bw.id %}" class="btn btn-warning btn-sm">detail</a>
                      <a href="{% url 'bodyweight:update' bw.id %}" class="btn btn-primary btn-sm">ubah</a>
                      <a href="{% url 'bodyweight:delete' bw.id %}" class="btn btn-danger btn-sm" onclick="return confirm('Apakah yakin akan menghapus record ini?')">hapus</a>
                  </td>
              </tr>
              {% endfor %}
            {% else %}
              <tr>
                <td colspan="5">Data tidak ditemukan.</td>
              </tr>
            {% endif %}
          </tbody>
      </table>

      <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th width="5%"> </th>
                <th width="25%">Rata-Rata</th>
                <th width="10%">Max</th>
                <th width="10%">Min</th>
                <th width="10%">Perbedaan</th>
                <th width="25%"> </th>
            </tr>
        </thead>
        <tbody>
            <td> </td>
            <td> </td>
            <td> </td>
            <td> </td>
            <td> </td>
        </tbody>
    </table>
  </div>
 
  </body>
</html>